name: Cicd-pipeline

on:
push:
        branches:
            -develop

jobs:
    deploy:
        runs_on: ubunutu-latest
    steps:
        -name: Checkout code
        uses: action\checkout@v2
        -name: Setup Node.js
        uses: action\Setup-node@v2

        with:
            node-version: '20'

-name: Install Dependencies
run: npm install

-name: Build Applications
run: npm run build

main 
pull_request:
    branches:
main